import numpy as np

a = np.array([[10, 2, 3, 4, 5], [1, 2, 9, 4, 5], [1, 2, 3, 4, 5]])
b = np.array([[3, 4, 5, 6, 7], [3, 9, 6, 6, 7], [3, 4, 5, 6, 7], [3, 4, 11, 6, 7], [3, 4, 5, 6, 7], [3, 4, 5, 6, 1]])

a2 = np.sum(a ** 2, axis=1).reshape(3, 1)
b2 = np.sum(b ** 2, axis=1).reshape(1, 6)
ab = np.dot(a, b.T)
print("a:----------------------")
print(a)
print("b.T:----------------------")
print(b.T)
print("a2----------------------")
print(a2)
print("b2----------------------")
print(b2)
print("ab----------------------")
print(ab)
print("a2 + b2----------------------")
print(a2 + b2)
print("a2 + ab----------------------")
print(a2 + ab)
print("b2 + ab----------------------")
print(b2 + ab)
print("a2 + b2 - 2 * ab----------------------")
print(a2 + b2 - 2 * ab)
